version: '3.4'
services:
  iotsharp:
    image: ${DOCKER_REGISTRY-}iotsharp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "2927:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./appsettings.Development.json:/app/appsettings.Development.json

    build:
      context: .
      dockerfile: IoTSharp/Dockerfile
  