
services:
  pgsql:
    image: timescale/timescaledb-ha:pg17
    volumes:
      - "./data/postgresql:/var/lib/postgresql"
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_USER: postgres
      POSTGRES_DB: IoTSharp
      POSTGRES_PASSWORD: BrrveCFVAZ6kM6vhjFMd 
    ports: 
     - "5432:5432"
    networks:
      - iotsharp-network
 
  iotsharp:
    image: maikebing/iotsharp
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - pgsql
    links:
      - pgsql
    volumes:
      - "./appsettings.Development.json:/app/appsettings.Development.json"
      - ./data/security:/app/security
    ports:
      - 2927:8080
      - 1883:1883
      - 8883:8883 
      - 5683:5683
      - 5684:5684
      - 502:502
    networks:
      - iotsharp-network
        
      

networks: 
  iotsharp-network:
      driver:  bridge
